Update aws_validator.yml

diff --git a/.github/workflows/aws_validator.yml b/.github/workflows/aws_validator.yml
--- a/.github/workflows/aws_validator.yml
+++ b/.github/workflows/aws_validator.yml
@@ -1,5 +1,3 @@
-# .github/workflows/validate-aws-credentials.yml
-
 name: Validate AWS Credentials
 
 on:
@@ -28,20 +26,27 @@ jobs:
           echo "ENV=TEST" >> $GITHUB_ENV
           echo "AWS_DEFAULT_REGION=eu-central-1" >> $GITHUB_ENV
 
-      - name: Create AWS config directory
-        run: mkdir -p ~/.aws
+      - name: Verify AWS secrets are set
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        run: |
+          if [[ -z "$AWS_ACCESS_KEY_ID" || -z "$AWS_SECRET_ACCESS_KEY" ]]; then
+            echo "AWS secrets are missing or empty."
+            exit 1
+          else
+            echo "AWS secrets are set."
+          fi
 
       - name: Configure AWS credentials
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         run: |
+          mkdir -p ~/.aws
           echo "[default]" > ~/.aws/credentials
           echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
           echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials
-
-      - name: Configure AWS region
-        run: |
           echo "[default]" > ~/.aws/config
           echo "region = eu-central-1" >> ~/.aws/config
 
